### ISSUE TITLE
Enzyme usage

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACEcore.jl#7]
This code can also be found at the end of `profile/profile_1pbasis.jl`
```julia
# enzyme version: 
Ae = zeros(length(A1))       # output for feature vector
∂BBe = map(zero, bBB)     # 
autodiff(Reverse, ACEcore.evalpool!, Const, Duplicated(Ae, ∂A), Const(basis), 
         Duplicated(bBB, ∂BBe))

@show norm.(∂BBe)
# norm.(∂BBe) = (0.0, 0.0, 0.0)
```
This would suggest I'm using it incorrectly but looking at [the documentation](https://docs.juliahub.com/Enzyme/G1p5n/0.10.12/pullbacks/#Example) doesn't give me a useful hint.

For the record, here is original code from @vchuravy : 
```julia 
using Enzyme

BB = ( randn(nX, N1), randn(nX, N2), randn(nX, N3) )
∂BB = map(zero, BB)

A = zeros(100)
dA = ones(100)

autodiff(Reverse, evalpool!, Const, Duplicated(A, dA), Const(basis), Duplicated(BB, ∂BB))
```

**Comment by cortner** [comment]
please disregard - the problem seems to have been some corrupted array. On a clean restarted script it is fine. apologies for the noise. 

Timings: 
```
# evaluation + pooling
  1.325 μs (0 allocations: 0 bytes)
# manual adjoint
  15.542 μs (5 allocations: 41.17 KiB)
# Enzyme adjoint -- wow!
  15.708 μs (0 allocations: 0 bytes)
```
I'm actually not thrilled with that performance yet, I'm targeting more a factor 2-4 of evaluation performance. But still very impressive.

**Comment by vchuravy** [comment]
CC @wsmosesThe overhead number are slightly hire than I would be expecting so we are likely caching a fair bit.

`Enzyme.API.printall!(true)` let's you see the code we are synthesizing. Also as I mentioned yesterday this is doing the forward+reverse code together. Do you need split mode for this?
